### ISSUE TITLE
Hi-Ether Meetup - Block 1 を開催する

### ISSUE THREAD

**Issue by june29** [hi-ether/meetup#1]
### やること

Block 0 の準備を思い出しながらタスクリストにしてみました。思い付いたら追記します。

- [x] 日程を決める
- [x] 会場を決める
- [x] スピーカーを決める
- [x] LT スピーカーを決める
- [x] タイムテーブルをつくる
- [x] 参加登録を開始する
- [x] 食べもの・飲みものを手配する
- [x] 開催する！

### ぼやき

本当は `Block #0` `Block #1` と書きたいけれど、GitHub だと Issue や Pull Request へのリンクになってしまうのでシャープはあきらめました :joy:

**Comment by june29** [comment]
@june29 は「LT スピーカーを決める」「タイムテーブルをつくる」をまとめて進めている、というステータスです :memo:

**Comment by june29** [comment]
「LT スピーカーを決める」「タイムテーブルをつくる」を Done しました。次は参加登録を開始できるように進めていきます。

「飲食の手配、手伝っていいよ〜」という方がいたらお任せしたいな。おりましたら :raising_hand_woman: をお願いします :wink:

**Comment by toshiakitakase** [comment]
何か必要であればお手伝いしますよ^^ 🙋

**Comment by ochibal2525** [comment]
お手伝いします : ) 🙋

**Comment by june29** [comment]
@toshiakitakase @ochibal2525 おお〜、とってもありがたいです！

それでしたら、食べもの・飲みものの手配をお願いしたいです。「Block 0 のときは、どうだったか」のデータがあるときっと進めやすいですよね。ちょっと探してみますね。

**Comment by toshiakitakase** [comment]
OKです！
お願いします^^あと予算感などあれば。
@ochibal2525 とは知り合いなので連携しておきます^^

**Comment by ochibal2525** [comment]
@june29 よろしくお願いいたします^^

**Comment by june29** [comment]
Block 0 は 80 人弱参加で、以下のような感じでした！(相談チャットのログ)

```
ケータリングどうしようかな〜と思っているのですが
80人ということなので　7~8万円とすると
・ピザ3000円弱 * 10弱 3万 https://pizza.dominos.jp/ja/menu
・ケータリング https://shop.munchiesdeli.com/
サンドイッチ  5500円 1ケース
ハムとかつまむやつ 6000円 2ケース
・ドリンク http://www.kakuyasu.co.jp/
2万 よしなに
```

**Comment by toshiakitakase** [comment]
OKです！

#meetupチャンネル見るかぎり、今回は
- 人数とタイムスケジュールは同様なものを想定
- 20:30頃目安に届くように発注
- 予算7万円程度にする（前回8万円弱で不足してしまったとのことなので）
- 飲み物は前回よりもちょい少なめ
- 食い物よしなに

って感じですかね^^

**Comment by june29** [comment]
なんとか参加登録の受付を開始できた！

あとは挙手してくれたおふたりと飲食の準備をしつつ、当日の受付や集金、タイムキーピングのことなどを考えていこう。

**Comment by ochibal2525** [comment]
@june29 
今回の注文ですが、
ケータリング 1万5000円（約600円 ×20人前）
ピザ ×10 3万ちょい
飲み物 18000円 （200円×90人前）

で65000ぐらいを想定してますが、こんな感じでよろしいでしょうか？^^

**Comment by june29** [comment]
書いていただいた内容でよさそうです！

**Comment by ochibal2525** [comment]
@june29 
承知しました!

**Comment by june29** [comment]
いよいよ今夜開催！

- 今日 @june29 は渋谷でお仕事しているので、早めに会場入りするつもりです
- 2〜3名程度、受付を手伝ってくれる人がいるとありがたいです :pray:
  - 受付のピークを終えたあとは、そのまま食べもの・飲みものを受け取る係になる見込みです :pizza: :beer:
- 写真を撮るのが得意！って方がいたらぜひ Meetup の様子を撮ってください :camera_flash:
  - @june29 もいちおうデジカメを持ってきました

参加者向けには、このあと下記をアナウンスしていこう。

- ご自身の受付番号がわかると、受付がスムーズです :ok_hand:
- キャンセル待ちの方がいらっしゃるので、参加できなくなった方はキャンセルをお願いします :bow:

**Comment by ochibal2525** [comment]
@june29 ケータリング受取もあるので、そのまま受付やります^^

**Comment by toshiakitakase** [comment]
お手伝いいたしますー^^

**Comment by june29** [comment]
@ochibal2525 @toshiakitakase おお、神よ…！いっしょにがんばりましょ〜 :sparkles: :muscle:

**Comment by toshiakitakase** [comment]
@june29 
何時入りすればよろしいですか？

**Comment by june29** [comment]
受付開始が 19:00 なので、ちょっと事前にお打ち合わせすることを考えると 18:45 にいてもらえたら最高という感じです！ただ 19:00 くらいになっても問題はありません。

ぼくも 18:45 には会場に存在するようにします :dash:

**Comment by mach** [comment]
私も早めに参ります〜

**Comment by june29** [comment]
### Block 1 も盛り上がりました！

発表されたみなさん、参加されたみなさん、運営のみなさん、おつかれさまでした！無事に開催できたのでこの Issue は Close しちゃいます :dash:

### ちょっとしたレポート

定員 80 人での募集に対して参加申し込みが 92 人で、受付で確認できた出席者は 81 人でした！昨今、都内での技術系イベントは「登録したまま不参加」も多くて運営が苦労しているところもたくさんある中で、Hi-Ether の健全な感じはすばらしいですね〜 :relaxed:

### 次回以降に向けて

タスクリストはこんな感じで :memo:
Block 1 では「ゴミの捨て方」の考慮が漏れていたのでバタバタしました :innocent:

やがさきさんが「ゴミ袋を買ってきます！」と動いてくれたので命拾いしました :pray:

```
- [ ] 日程を決める
- [ ] 会場を決める
- [ ] スピーカーを決める
- [ ] LT スピーカーを決める
- [ ] タイムテーブルをつくる
- [ ] 参加登録を開始する
- [ ] 食べもの・飲みものを手配する
- [ ] 会場の「ゴミの捨て方」を確認して備えておく
- [ ] 前日〜当日あたりに諸情報を含めたリマインドをする
- [ ] 開催する！
```

これくらいあれば開催できそう〜というロールたち (右側は今回やった人) :memo:

- 会場予約 1 人 : @mach 
- コンテンツ委員 1〜2 人 : @mach @june29
- 受付 3 人 : @ochibal2525 @toshiakitakase @june29
- 会計 1 人 : @ochibal2525 @june29
- 司会 1 人 : @mach 
- 飲食手配 1〜2 人 : @ochibal2525 @toshiakitakase 
- タイムキーパー 1 人 : @june29
- イベントページ準備 1 人 : @mach @june29
